version: '3.5'

services:
  busybox:
    container_name: "busybox"
    image: "busybox"
    command: top
    volumes:
      - "./:/deploy:rw"
      - "/etc/dnsmasq.d/:/ipset:rw"
    networks:
      desktopwork:
        ipv4_address: 172.111.11.5
    restart: unless-stopped
  nginx:
    container_name: "nginx-desktop"
    hostname: nginx-desktop
    image: "openresty/openresty:alpine"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "/tmp:/tmp"
      - "./nginx/conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf"
      - "./nginx/conf/conf.d:/etc/nginx/conf.d"
      - "./nginx/lua:/usr/local/openresty/nginx/lua"
      - "./logs:/var/log"
    networks:
      desktopwork:
        ipv4_address: 172.111.11.6
    restart: unless-stopped

networks:
  desktopwork:
    name: "M-desktop-network"
    ipam:
      config:
        - subnet: 172.111.0.0/16
          gateway: 172.111.11.1